# Generated by Django 3.2.7 on 2021-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctioneer', models.CharField(max_length=50)),
                ('auction_winner', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
