# Generated by Django 3.1.2 on 2021-11-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0003_auto_20211015_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_end',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_start',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
