# Generated by Django 3.1.2 on 2021-11-11 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0004_auto_20211105_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=200)),
                ('reserve_price', models.IntegerField()),
                ('sequential_uuid', models.IntegerField()),
                ('minimal_bid', models.IntegerField()),
                ('lot_photo', models.CharField(max_length=200)),
                ('seller_contact', models.IntegerField()),
                ('lot_description', models.CharField(max_length=200)),
                ('minimum_bid_increment', models.IntegerField()),
                ('comissions', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('number_of_bids_made', models.IntegerField()),
                ('current_winner_buyer', models.CharField(max_length=200)),
                ('highest_value_bid', models.IntegerField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctioneer.auction')),
            ],
        ),
    ]
