# Generated by Django 2.2.24 on 2021-11-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0006_auto_20211111_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_photo',
        ),
    ]
