# Generated by Django 3.1.2 on 2021-11-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0007_remove_lot_lot_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='auction_ref_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
