# Generated by Django 3.1.2 on 2021-11-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0008_lot_auction_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_published',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
