# Generated by Django 2.2.24 on 2021-11-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_auto_20211105_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_photo',
        ),
    ]
