# Generated by Django 2.2.24 on 2021-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_user', '0003_auto_20211105_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='seller_contact',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lot',
            name='sequential_uuid',
            field=models.CharField(max_length=200),
        ),
    ]
