# Generated by Django 2.2.24 on 2021-11-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot_user', '0004_auto_20211112_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_photo',
        ),
    ]
